export enum ShoppingCartTypes {
 ADD_PRODUCT_TO_CART = '@SHOPPING_CART/ADD_PRODUCT_TO_CART',
 REMOVE_PRODUCT_FROM_CART = '@SHOPPING_CART/REMOVE_PRODUCT_FROM_CART',
 QUANTITY_ADD_ONE = '@SHOPPING_CART/QUANTITY_ADD_ONE',
 QUANTITY_REMOVE_ONE = '@SHOPPING_CART/QUANTITY_REMOVE_ONE',
 ADD_ACTIVE_PRODUCT = '@SHOPPING_CART/ADD_ACTIVE_PRODUCT',
 REMOVE_ACTIVE_PRODUCT = '@SHOPPING_CART/REMOVE_ACTIVE_PRODUCT',
 CLEAR_CART = 'CLEAR_CART'
}
